[project]
name = "open-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evdev>=1.9.2",
    "openai>=2.6.1",
    "pynput>=1.8.1",
    "pyscreenshot>=3.1",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "ruff>=0.14.2",
    "types-pynput>=1.8.1.20250809",
]
